### ISSUE TITLE
It is possible to create invalid task config

### ISSUE THREAD

**Issue by alex-slynko** [akshaymankar/dhall-concourse#1]
😱😱😱
The developer has to specify `image_resource` or `rootfs_uri`  in TaskConfig

Otherwise, you get a nice orange task with the error
```
no image plugin configured
```

**Comment by akshaymankar** [comment]
The developer doesn't really have to specify any of those. If a TaskConfig doesn't have both of those properties, the developer can still run it in concourse by specifying `image` in TaskStep. [Concourse Docs](https://concourse-ci.org/task-step.html#task-step-image).

It would be cool if dhall-concourse could type check this, but it would makes types too complicated, so I think the types are fine as they are.
